name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          extensions: gmp
          tools: composer:v2, phpunit
      - name: Install dependencies
        run: composer install && composer update --no-scripts
      - name: Migrate phpunit.xml
        run: ./vendor/bin/phpunit --migrate-configuration
      - name: Run coverage
        run: ./vendor/bin/phpunit --coverage-xml coverage
      - uses: docker/login-action@v2
        if: ${{ always() }} 
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACE_REGISTRY_PASSWORD }}
      - name: 'Qodana Scan'
        if: ${{ always() }}
        uses: JetBrains/qodana-action@main
