name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: gmp
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
