name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: gmp
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr-mode: false
          args: --apply-fixes
          push-fixes: pull-request
          upload-result: true