name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:


jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: gmp
      - name: PHPUnit tests
        continue-on-error: true
        uses: php-actions/phpunit@v3
        with:
          configuration: "phpunit.xml.dist"
          php_extensions: "xdebug"
          coverage_clover: "./.qodana/code-coverage/coverage.xml"
      - uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACE_REGISTRY_PASSWORD }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
